Repository livgust/macovidvaccines.com, pull requests merged in 2021-03, with the labels that each got.

#92 Google Maps links
  src/components/MoreInformation.js
Labels: UX enhancement

#78 Future-proof tests from being dependent on the system date and time
  src/components/Availability.js
  src/components/StaleDataIndicator.js
  src/components/StaleDataIndicator.test.js
Labels: architecture

#129 Refactor AlertBanner out of App.js
  src/App.js
  src/components/AlertBanner.js
Labels: enhancement

#111 Configure react-i18n for future translations
  package-lock.json
  package.json
  src/App.js
  src/components/Availability.js
  src/i18n.js
  src/index.js
  src/setupTests.js
  src/translations/translations.en.main.json
Labels: architecture

#150 New state eligibility dates
  src/components/StateEligibility.js
Labels: urgent
